services:
  backend_api:
    build:
      context: ./backend
      target: development
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/envs/backend_env.env
