# Generated by Django 4.2 on 2023-04-28 09:55

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LinkShortcut",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_link", models.URLField()),
                ("shortcut", models.CharField(max_length=10, unique=True)),
            ],
            options={
                "verbose_name_plural": "Link shortcuts",
            },
        ),
    ]
